spring:
  connfig:
     activate:
        on-profile: test
  datasource:
    url: jdbc:h2:mem:shorter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 